/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import Utils.XImage;

/**
 *
 * @author 84963
 */
public class HelloFrame extends javax.swing.JFrame {

    /**
     * Creates new form HelloFrame
     */
    public HelloFrame() {
        this.setLocationRelativeTo(null);
        initComponents();
        setIconImage(XImage.getAppIcon());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblsus = new javax.swing.JLabel();
        lblhello = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, -30, -1, -1));

        lblsus.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lblsus.setForeground(new java.awt.Color(255, 102, 0));
        lblsus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblsus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblsus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 390, 20));

        lblhello.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblhello.setForeground(new java.awt.Color(255, 102, 0));
        lblhello.setText(" 99%");
        getContentPane().add(lblhello, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, -1, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/firecode_final.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, -1, -1));

        progressBar.setBackground(new java.awt.Color(255, 102, 0));
        progressBar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        progressBar.setForeground(new java.awt.Color(255, 102, 0));
        getContentPane().add(progressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 850, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/laoding_final.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelloFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelloFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelloFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelloFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        HelloFrame hl = new HelloFrame();
        hl.setVisible(true);
        try {
            for (int i = 0; i <= 100; i++) {
                Thread.sleep(20);
                hl.lblhello.setText(Integer.toString(i) + "%");
                hl.progressBar.setValue(i);
                if (1 < i && i < 55) {
                    String x = "Xin Chào Các Bạn!!";
                    hl.lblsus.setText(x);
                }
                if (55 < i && i < 80) {
                    String x = "Đang kết nối!!";
                    hl.lblsus.setText(x);
                } else if (80 < i && i < 101) {
                    String y = "Đang Vào giao diện đăng nhập !!";
                    hl.lblsus.setText(y);
                }

            }
            hl.dispose();
            new DangNhap().setVisible(true);
        } catch (Exception e) {
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblhello;
    private javax.swing.JLabel lblsus;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables

}
