/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import DAO.KhachHangDAO;
import Entity.KhachHang;
import Utils.MsgBox;
import Utils.XDate;
import Utils.XExcel;
import java.awt.Color;
import java.awt.Font;
import java.util.Iterator;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Vu Hoang Phuc
 */
public class QuanLyKhachHangJPanel extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyKhachHangJPanel
     */
    public QuanLyKhachHangJPanel() {
        initComponents();
        fillTable();
        txtMaKhachHang.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtTenKhachHang.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtDiaChi.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtEmail.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtNgaySinh.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtSDT.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtTimKhachHang.setBackground(new java.awt.Color(0, 0, 0, 1));
        this.CanChinhTable();
        
        JTableHeader header = tblKhachHang.getTableHeader();
        header.setBackground(Color.cyan);
        header.setForeground(Color.black);
        header.setFont(new Font("Tahoma", Font.BOLD, 12));
        this.updateStatus();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        btnPrev = new keeptoo.KButton();
        btnNext = new keeptoo.KButton();
        btnLast = new keeptoo.KButton();
        btnFirst = new keeptoo.KButton();
        kButton2 = new keeptoo.KButton();
        jLabel1 = new javax.swing.JLabel();
        txtTimKhachHang = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhachHang = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        kGradientPanel5 = new keeptoo.KGradientPanel();
        btnXoa = new keeptoo.KButton();
        btnSua = new keeptoo.KButton();
        btnMoi = new keeptoo.KButton();
        btnThem = new keeptoo.KButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTenKhachHang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        txtMaKhachHang = new javax.swing.JLabel();

        jLabel9.setText("jLabel9");

        setOpaque(false);

        kGradientPanel1.setOpaque(false);

        kGradientPanel3.setOpaque(false);
        kGradientPanel3.setLayout(null);

        kGradientPanel4.setkEndColor(new java.awt.Color(153, 204, 255));
        kGradientPanel4.setkStartColor(new java.awt.Color(153, 204, 255));
        kGradientPanel4.setOpaque(false);
        kGradientPanel4.setLayout(null);

        btnPrev.setText("<<");
        btnPrev.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });
        kGradientPanel4.add(btnPrev);
        btnPrev.setBounds(100, 10, 88, 38);

        btnNext.setText(">>");
        btnNext.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        kGradientPanel4.add(btnNext);
        btnNext.setBounds(200, 10, 88, 38);

        btnLast.setText(">|");
        btnLast.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        kGradientPanel4.add(btnLast);
        btnLast.setBounds(300, 10, 83, 38);

        btnFirst.setText("|<");
        btnFirst.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        kGradientPanel4.add(btnFirst);
        btnFirst.setBounds(10, 10, 82, 40);

        kButton2.setText("Export Excel");
        kButton2.setkEndColor(new java.awt.Color(255, 153, 51));
        kButton2.setkStartColor(new java.awt.Color(255, 51, 0));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        kGradientPanel4.add(kButton2);
        kButton2.setBounds(390, 10, 83, 38);

        kGradientPanel3.add(kGradientPanel4);
        kGradientPanel4.setBounds(10, 550, 480, 60);

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DANH SÁCH KHÁCH HÀNG");
        kGradientPanel3.add(jLabel1);
        jLabel1.setBounds(20, 20, 370, 40);

        txtTimKhachHang.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        txtTimKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        txtTimKhachHang.setText("Tìm kiếm");
        txtTimKhachHang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtTimKhachHang.setOpaque(false);
        txtTimKhachHang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimKhachHangFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTimKhachHangFocusLost(evt);
            }
        });
        txtTimKhachHang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKhachHangKeyReleased(evt);
            }
        });
        kGradientPanel3.add(txtTimKhachHang);
        txtTimKhachHang.setBounds(30, 70, 420, 30);

        tblKhachHang.setBackground(new java.awt.Color(204, 204, 255));
        tblKhachHang.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã KH", "Tên Khách Hàng", "Địa Chỉ", "SDT", "Ngày Sinh", "Email", "Giới Tính "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKhachHang.setRowHeight(25);
        tblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhachHang);

        kGradientPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(20, 120, 469, 402);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/find.png"))); // NOI18N
        kGradientPanel3.add(jLabel10);
        jLabel10.setBounds(460, 70, 30, 30);

        kGradientPanel2.setForeground(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setkGradientFocus(100);
        kGradientPanel2.setOpaque(false);
        kGradientPanel2.setPreferredSize(new java.awt.Dimension(370, 620));
        kGradientPanel2.setLayout(null);

        kGradientPanel5.setkEndColor(new java.awt.Color(153, 204, 255));
        kGradientPanel5.setkStartColor(new java.awt.Color(153, 204, 255));
        kGradientPanel5.setOpaque(false);
        kGradientPanel5.setLayout(null);

        btnXoa.setText("Xóa");
        btnXoa.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        kGradientPanel5.add(btnXoa);
        btnXoa.setBounds(110, 10, 70, 37);

        btnSua.setText("Sửa");
        btnSua.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        kGradientPanel5.add(btnSua);
        btnSua.setBounds(190, 10, 72, 37);

        btnMoi.setText("Mới");
        btnMoi.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });
        kGradientPanel5.add(btnMoi);
        btnMoi.setBounds(270, 10, 72, 37);

        btnThem.setText("Thêm");
        btnThem.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        kGradientPanel5.add(btnThem);
        btnThem.setBounds(20, 10, 75, 37);

        kGradientPanel2.add(kGradientPanel5);
        kGradientPanel5.setBounds(10, 549, 348, 60);

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mã Khách Hàng:");
        kGradientPanel2.add(jLabel2);
        jLabel2.setBounds(20, 120, 120, 33);

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tên Khách Hàng:");
        kGradientPanel2.add(jLabel3);
        jLabel3.setBounds(10, 170, 130, 33);

        txtTenKhachHang.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        txtTenKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        txtTenKhachHang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtTenKhachHang.setOpaque(false);
        txtTenKhachHang.setPreferredSize(new java.awt.Dimension(7, 15));
        txtTenKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenKhachHangActionPerformed(evt);
            }
        });
        kGradientPanel2.add(txtTenKhachHang);
        txtTenKhachHang.setBounds(140, 170, 200, 30);

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Địa Chỉ:");
        kGradientPanel2.add(jLabel4);
        jLabel4.setBounds(70, 240, 70, 33);

        txtDiaChi.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        txtDiaChi.setForeground(new java.awt.Color(255, 255, 255));
        txtDiaChi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtDiaChi.setOpaque(false);
        txtDiaChi.setPreferredSize(new java.awt.Dimension(7, 15));
        txtDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaChiActionPerformed(evt);
            }
        });
        kGradientPanel2.add(txtDiaChi);
        txtDiaChi.setBounds(140, 243, 200, 30);

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Số Điện Thoại:");
        kGradientPanel2.add(jLabel5);
        jLabel5.setBounds(20, 300, 120, 33);

        txtSDT.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        txtSDT.setForeground(new java.awt.Color(255, 255, 255));
        txtSDT.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtSDT.setOpaque(false);
        txtSDT.setPreferredSize(new java.awt.Dimension(7, 15));
        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });
        kGradientPanel2.add(txtSDT);
        txtSDT.setBounds(140, 300, 200, 33);

        jLabel6.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ngày Sinh:");
        kGradientPanel2.add(jLabel6);
        jLabel6.setBounds(50, 360, 90, 30);

        txtNgaySinh.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        txtNgaySinh.setForeground(new java.awt.Color(255, 255, 255));
        txtNgaySinh.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtNgaySinh.setOpaque(false);
        txtNgaySinh.setPreferredSize(new java.awt.Dimension(7, 15));
        txtNgaySinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgaySinhActionPerformed(evt);
            }
        });
        kGradientPanel2.add(txtNgaySinh);
        txtNgaySinh.setBounds(140, 350, 200, 34);

        jLabel7.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email:");
        kGradientPanel2.add(jLabel7);
        jLabel7.setBounds(80, 420, 50, 34);

        txtEmail.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtEmail.setOpaque(false);
        txtEmail.setPreferredSize(new java.awt.Dimension(7, 15));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        kGradientPanel2.add(txtEmail);
        txtEmail.setBounds(140, 410, 200, 34);

        jLabel8.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Giới Tính:");
        kGradientPanel2.add(jLabel8);
        jLabel8.setBounds(60, 470, 80, 20);

        buttonGroup1.add(rdoNam);
        rdoNam.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        rdoNam.setForeground(new java.awt.Color(255, 255, 255));
        rdoNam.setSelected(true);
        rdoNam.setText("Nam");
        rdoNam.setOpaque(false);
        kGradientPanel2.add(rdoNam);
        rdoNam.setBounds(160, 470, 60, 25);

        buttonGroup1.add(rdoNu);
        rdoNu.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        rdoNu.setForeground(new java.awt.Color(255, 255, 255));
        rdoNu.setText("Nữ");
        rdoNu.setOpaque(false);
        rdoNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNuActionPerformed(evt);
            }
        });
        kGradientPanel2.add(rdoNu);
        rdoNu.setBounds(240, 470, 41, 25);

        txtMaKhachHang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMaKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        kGradientPanel2.add(txtMaKhachHang);
        txtMaKhachHang.setBounds(140, 120, 126, 30);

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(kGradientPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kGradientPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kGradientPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        this.prev();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        this.next();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        this.last();
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:\
        this.first();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        this.delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        this.update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        // TODO add your handling code here:
        this.clearForm();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        this.insert();
    }//GEN-LAST:event_btnThemActionPerformed

    private void txtTimKhachHangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKhachHangKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblKhachHang.getModel();
        model.setRowCount(0);
        String keyword = txtTimKhachHang.getText();
        List<KhachHang> list = dao.selectNotInCourse(keyword);
        for (KhachHang kh : list) {
            model.addRow(new Object[]{
                kh.getMAKH(),
                kh.getTENKH(),
                kh.getDIACHI(),
                kh.getSDT(),
                kh.getNGAYSINH(),
                kh.getEMAIL(),
                kh.getGIOITINH() ? "Nam" : "Nữ",});
        }
    }//GEN-LAST:event_txtTimKhachHangKeyReleased

    private void tblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {
            this.row = tblKhachHang.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tblKhachHangMouseClicked

    private void txtTenKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenKhachHangActionPerformed

    private void txtDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaChiActionPerformed

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTActionPerformed

    private void txtNgaySinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgaySinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgaySinhActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void rdoNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNuActionPerformed

    private void txtTimKhachHangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKhachHangFocusGained
        // TODO add your handling code here:
        if (txtTimKhachHang.getText().equals("Tìm kiếm")) {
            txtTimKhachHang.setText("");
        }
    }//GEN-LAST:event_txtTimKhachHangFocusGained

    private void txtTimKhachHangFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKhachHangFocusLost
        // TODO add your handling code here:
        if (txtTimKhachHang.getText().equals("")) {
            txtTimKhachHang.setText("Tìm kiếm");
        }
    }//GEN-LAST:event_txtTimKhachHangFocusLost

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        // TODO add your handling code here:
        XExcel a = new XExcel();
        a.exportToExcels(tblKhachHang);
    }//GEN-LAST:event_kButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnFirst;
    private keeptoo.KButton btnLast;
    private keeptoo.KButton btnMoi;
    private keeptoo.KButton btnNext;
    private keeptoo.KButton btnPrev;
    private keeptoo.KButton btnSua;
    private keeptoo.KButton btnThem;
    private keeptoo.KButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KButton kButton2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel4;
    private keeptoo.KGradientPanel kGradientPanel5;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTable tblKhachHang;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JLabel txtMaKhachHang;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenKhachHang;
    private javax.swing.JTextField txtTimKhachHang;
    // End of variables declaration//GEN-END:variables

    KhachHangDAO dao = new KhachHangDAO();
    int row = -1;
    
 
    void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblKhachHang.getModel();
        model.setRowCount(0);
        try {
            String keyword = txtTimKhachHang.getText();
            //  List<KhachHang> tk = dao.selectByKeyword(keyword);
            List<KhachHang> list = dao.selectAll();
            for (KhachHang kh : list) {
                Object[] row = {
                    kh.getMAKH(),
                    kh.getTENKH(),
                    kh.getDIACHI(),
                    kh.getSDT(),
                    kh.getNGAYSINH(),
                    kh.getEMAIL(),
                    kh.getGIOITINH() ? "Nam" : "Nữ",
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn");
        }
    }

    void setForm(KhachHang kh) {
        txtMaKhachHang.setText(String.valueOf(kh.getMAKH()));
        txtTenKhachHang.setText(kh.getTENKH());
        txtDiaChi.setText(kh.getDIACHI());
        txtSDT.setText(kh.getSDT());
        txtNgaySinh.setText(XDate.toString(kh.getNGAYSINH(), "dd/MM/yyyy"));
        txtEmail.setText(kh.getEMAIL());
        if (kh.getGIOITINH()) {
            rdoNam.setSelected(true);
        } else {
            rdoNu.setSelected(true);
        }
    }

    KhachHang getForm() {
        KhachHang kh = new KhachHang();
        kh.setMAKH(Integer.valueOf(txtMaKhachHang.getText()));
        kh.setTENKH(txtTenKhachHang.getText());
        kh.setDIACHI(txtDiaChi.getText());
        kh.setSDT(txtSDT.getText());
        kh.setNGAYSINH(XDate.toDate(txtNgaySinh.getText(), "dd/MM/yyyy"));
        kh.setEMAIL(txtEmail.getText());
        kh.setGIOITINH(rdoNam.isSelected());
        return kh;
    }

    KhachHang getForm1() {
        KhachHang kh = new KhachHang();
//        kh.setMAKH(Integer.valueOf(txtMaKhachHang.getText()));
        kh.setTENKH(txtTenKhachHang.getText());
        kh.setDIACHI(txtDiaChi.getText());
        kh.setSDT(txtSDT.getText());
        kh.setNGAYSINH(XDate.toDate(txtNgaySinh.getText(), "dd/MM/yyyy"));
        kh.setEMAIL(txtEmail.getText());
        kh.setGIOITINH(rdoNam.isSelected());
        return kh;
    }

    void edit() {
        Integer manv = (Integer) tblKhachHang.getValueAt(this.row, 0);
        KhachHang nv = dao.selectById(manv);
        this.setForm(nv);
        this.updateStatus();
    }

    void clearForm() {
        txtMaKhachHang.setText("");
        txtTenKhachHang.setText("");
        txtDiaChi.setText("");
        txtSDT.setText("");
        txtNgaySinh.setText("");
        txtEmail.setText("");
        this.row = -1;
        this.updateStatus();
    }

    void delete() {
        if (MsgBox.confirm(this, "Bạn thực sự muốn xoá khách hàng này ?")) {
            Integer makh = Integer.valueOf(txtMaKhachHang.getText());
            try {
                dao.delete(makh);
                this.fillTable();
                this.clearForm();
                MsgBox.alert(this, "Xoá thành công");
            } catch (Exception e) {
                MsgBox.alert(this, "Xoá thất bại");
            }
        }
    }

    void update() {
        if (!validates()) {
            return;
        } else {
            KhachHang model = this.getForm();
            try {
                dao.update(model);
                this.fillTable();
                MsgBox.alert(this, "Cập nhật thành công");
            } catch (Exception e) {
                MsgBox.alert(this, "Cập nhật thất bại" + e);
            }
        }
    }

    void insert() {
        if (!validates()) {
            return;
        } else {
            KhachHang model = getForm1();
            try {
                dao.insert(model);
                this.fillTable();
                this.clearForm();
                MsgBox.alert(this, "Thêm mới thành công");
            } catch (Exception e) {
                MsgBox.alert(this, "Thêm mới thất bại" + e);
            }
        }
    }

      boolean validates() {
        if (txtTenKhachHang.getText().equals("")) {
            MsgBox.alert(this, "Tên khách hàng không được rỗng");
            txtTenKhachHang.requestFocus();
            return false;
        }

        if (txtSDT.getText().equals("")) {
            MsgBox.alert(this, "Số điện thoại không được rỗng");
            txtSDT.requestFocus();
            return false;

        }
        boolean flag;
        do {
            String phonePattern = "((09|03|07|08|05)+([0-9]{8}))|(1900+([0-9]{4,8}))";
            flag = txtSDT.getText().matches(phonePattern);
            if (!flag) {
                JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ");
                txtSDT.requestFocus();
                return false;
            }
        } while (!flag);

        do {
            String phonePattern = "(0?[1-9]|[12][0-9]|3[01])/(0?[1-9]|1[012])/((19|20)[0-9]{2})";
            flag = txtNgaySinh.getText().matches(phonePattern);
            if (!flag) {
                JOptionPane.showMessageDialog(this, "Ngày sinh không hợp lệ");
                txtNgaySinh.requestFocus();
                return false;
            }
        } while (!flag);

        do {
            if (!txtEmail.getText().equals("")) {
                String emailPattern = "(\\w+@\\w+[.]\\w+[.]\\w+)|(\\w+@\\w+[.]\\w+)";
                flag = txtEmail.getText().matches(emailPattern);
                if (!flag) {
                    JOptionPane.showMessageDialog(this, "Email không hợp lệ");
                    txtEmail.requestFocus();
                    return false;
                }
            }
        } while (!flag);
        return true;
    }


    void first() {
        if (tblKhachHang.getValueAt(this.row, 0) != null) {

            this.row = 0;
            tblKhachHang.setRowSelectionInterval(row, row);
            this.edit();
        }

    }

    void prev() {
        if (this.row > 0) {
            this.row--;
            tblKhachHang.setRowSelectionInterval(row, row);
            this.edit();
        }
    }

    void next() {
        if (this.row < tblKhachHang.getRowCount() - 1) {
            this.row++;
            tblKhachHang.setRowSelectionInterval(row, row);
            this.edit();
        }
    }

    void last() {
        this.row = tblKhachHang.getRowCount() - 1;
        tblKhachHang.setRowSelectionInterval(row, row);
        this.edit();
    }

    void updateStatus() {
        boolean edit = (this.row >= 0);
        boolean first = (this.row == 0);
        boolean last = (this.row == tblKhachHang.getRowCount() - 1);
        // Trạng thái form

        btnThem.setVisible(!edit);
        btnSua.setVisible(edit);
        btnXoa.setVisible(edit);

        // Trạng thái điều hướng
        btnFirst.setVisible(edit && !first);
        btnPrev.setVisible(edit && !first);
        btnNext.setVisible(edit && !last);
        btnLast.setVisible(edit && !last);
    }
    void CanChinhTable() {
        tblKhachHang.setAutoResizeMode(tblKhachHang.AUTO_RESIZE_OFF);
        tblKhachHang.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblKhachHang.getColumnModel().getColumn(1).setPreferredWidth(120);
        tblKhachHang.getColumnModel().getColumn(2).setPreferredWidth(50);
        tblKhachHang.getColumnModel().getColumn(3).setPreferredWidth(80);
        tblKhachHang.getColumnModel().getColumn(4).setPreferredWidth(80);
        tblKhachHang.getColumnModel().getColumn(5).setPreferredWidth(80);
        tblKhachHang.getColumnModel().getColumn(6).setPreferredWidth(40);
    }

}
